### ISSUE TITLE
Have version information (of the release) in the index.html

### ISSUE THREAD

**Issue by PaulBoon** [gdcc/dv-metrics#13]
Currently the metrics webpage (index.html) does not have the version number of the `dv-metrics` release used. 
This makes it cumbersome to check  what version has been deployed and thus  if upgrades have been done. 

The initial idea is to just add that version info to the footer of that page.

**Comment by PaulBoon** [comment]
Instead of 'hardcoding' it in the html footer we can add it as a meta tag in the html header; 
``` 
<meta name="version" content="1.2.0">
```
If we then want to show it on the page we don't want to duplicate it, but instead we can get the value and create some elements with JavaScript. For instance with jQuery you can get the version string like this: 
```
var version = $('meta[name=version]').attr('content');
```

This also allows to make the display optional and configurable. 

As a workaround my deploy (ansible) script now injects the version like this: 
```
- name: Inject version info
  lineinfile:
    path: "{{ metrics_extracted_app_path }}/index.html"
    insertbefore: '^(\s*)</head>(\s*)$'
    line: '    <meta name="version" content="{{ metrics_version }}">'
```
