### ISSUE TITLE
Provide layout configuration for drawing only one graph per row

### ISSUE THREAD

**Issue by PaulBoon** [gdcc/dv-metrics#8]
Most rows have two graphs (or charts), but on some DV instances the graphs are crammed and you want each one to have the whole row, so it has more space to render.

**Comment by PaulBoon** [comment]
Using jQuery add and remove class to change the layout makes loading/rendering of the page very slow. 
This probably improves if we do not use the `removeClass`, but only the add. The html wil not have that `col-md-*`, but needs some placholder there and then we add the collect class based on the config. 

I am tending towards not making this configurable. We could always explain in the documentation how to do this in the `index.html` file. This is not ideal, but very slow rendering is almost unacceptable.

**Comment by PaulBoon** [comment]
Until we have a good solution for making it configurable without making the page load very slow I want to close this issue.

**Comment by PaulBoon** [comment]
Instead of changing the `index.html` file 'manually, you could automate is when installing. 
For instance via ansible, like the following code sample:

```
- name: Make downloads graph take whole row width
  replace:
    path: "{{ metrics_extracted_app_path }}/index.html"
    regexp: 'class="col-xs-12 col-md-6"'
    replace: 'class="col-xs-12 col-md-12 replaced-col-md-6"'
    # limit to that div only
    after: '<div class="row">'
    before: '<div id="downloads" class="viz"></div>'

- name: Make uniquedownloads graph take whole row width
  replace:
    path: "{{ metrics_extracted_app_path }}/index.html"
    regexp: 'class="col-xs-12 col-md-6"'
    replace: 'class="col-xs-12 col-md-12 replaced-col-md-6"'
    # limit to that div only
    after: '<div class="row">'
    before: '<div id="uniquedownloads" class="viz"></div>'
```
